"""Phase G/H + D gate: the in-event cascade (pion-propagation) effect on the nu final state.

Uses the ACHILLES nu_e RES cascade off-vs-on summary (data/oracle/cascade_effect_nue_c12.csv,
generated by the achilles:fullcascade image -- the in-event-cascade fix; see PHASE_G.md):
  (1) the cascade physically SOFTENS the pion spectrum and absorbs ~22% to CC0pi;
  (2) the differentiable ToyCascadeFSI, tuned to the cascade (sigma_sc~0.17, sigma_abs~0.10),
      reproduces the CC0pi absorption fraction and the softening.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pathlib import Path

import numpy as np
import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import pytest

from adonis.core.event import EventRecord
from adonis.fsi.cascade import ToyCascadeFSI, CascadeConfig
from adonis.params import PhysicsParams

_CSV = Path(__file__).resolve().parents[1] / "data" / "oracle" / "cascade_effect_nue_c12.csv"
pytestmark = pytest.mark.skipif(not _CSV.exists(), reason="cascade-effect oracle CSV not present")
M_PI = 139.57


def _header():
    h = {}
    for line in _CSV.read_text().splitlines():
        if line.startswith("# cc0pi_off"):
            for tok in line[1:].split():
                k, v = tok.split("="); h[k] = float(v)
    return h


def test_cascade_softens_and_absorbs():
    """ACHILLES: the in-event cascade softens the pion spectrum (mean_on < mean_off) and
    absorbs a sizable CC0pi fraction (~22%)."""
    h = _header()
    assert h["mean_on"] < h["mean_off"] - 15            # softening (energy loss)
    assert 0.15 < h["cc0pi_on"] < 0.30                  # absorption -> CC0pi
    assert h["cc0pi_off"] < 1e-6                         # RES single-pi: every event has a pion


def test_toy_fsi_reproduces_cascade():
    """The tuned differentiable ToyCascadeFSI reproduces the ACHILLES CC0pi fraction and the
    softening, applied to a pion batch drawn from the cascade-OFF spectrum."""
    d = np.loadtxt(_CSV); ctr, off = d[:, 0], d[:, 1]
    h = _header()
    rng = np.random.default_rng(0)
    n = 20_000
    p = rng.choice(ctr, size=n, p=off / off.sum())
    dirs = rng.normal(size=(n, 3)); dirs /= np.linalg.norm(dirs, axis=1, keepdims=True)
    p3 = jnp.asarray(dirs * p[:, None]); E = jnp.sqrt(p ** 2 + M_PI ** 2); z = jnp.zeros((n, 4))
    ev = EventRecord(k=z, kp=z, p_struck=z, p_pi=jnp.concatenate([jnp.asarray(E)[:, None], p3], 1),
                     p_N=z, w=jnp.ones(n), channel=jnp.zeros(n, jnp.int32),
                     pid_pi=jnp.full(n, 211, jnp.int32), pid_N=jnp.full(n, 2212, jnp.int32),
                     pid_Ni=jnp.full(n, 2112, jnp.int32), W=jnp.full(n, 1232.0), Q2_adj=jnp.full(n, 1e5))
    fsi = ToyCascadeFSI(CascadeConfig(seed=3, oset_shape=True))
    out = fsi.apply(PhysicsParams(fsi_sigma_scatter=0.17, fsi_sigma_abs=0.10), ev, key=jax.random.PRNGKey(1))
    absb = np.asarray(out.pid_pi == 0); w = np.asarray(out.w)
    pm = np.asarray(jnp.linalg.norm(out.p_pi[:, 1:], axis=1))
    cc0 = w[absb].sum() / w.sum()
    mean_surv = np.average(pm[~absb], weights=w[~absb])
    assert abs(cc0 - h["cc0pi_on"]) < 0.06, (cc0, h["cc0pi_on"])    # matches ACHILLES CC0pi
    assert mean_surv < p.mean() - 5                                 # model also softens
